server:
  port: 8101
  servlet:
    context-path: /api

spring:
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: tianmu
    connection-timeout: 5s
    socket-timeout: 30s
  application:
    name: SearchSyncService
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:49152/tianmu?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root123456
  data:
    redis:
      database: 0
      host: localhost
      port: 59000
      timeout: 50000
      password: e65K4t8w2
      #    password: e65K4t8w2 # Redis 服务器密码（当前未启用）
      # 配置 redis 连接池
      lettuce:
        pool:
          # 链接池中最小的空闲链接 默认为 0
          min-idle: 4
          # 链接池中最大的空闲连接 默认为 8
          max-idle: 8
          #连接池中最大数据库链接数 默认为 8
          max-active: 8
          #连接池最大阻塞等待时间
          max-wait: 5000ms


canal:
  server:
    host: localhost
    port: 11111
  destination: example
  username: canal
  password: canal
  filter: ".*\\..*"
  client:
    heartbeat:
      interval: 2000    # 心跳间隔(毫秒)
      timeout: 3000    # 心跳超时(毫秒)
    socket:
      timeout: 6000    # socket超时(毫秒)